server:
  port : 8081

spring:
  kafka:
    bootstrap-servers: PLAINTEXT://:9092
    #bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3